name: CI/CD Docker

on:
  push:
    branches: [main, dev]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Installer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Se connecter à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Construire et pousser l'image Docker
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: tonPseudoDocker/demo-devops6:latest
